name: pulzion_25_app
description: Official App for Pulzion 25

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  csc_picker: ^0.2.7
  cupertino_icons: ^1.0.8
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  firebase_remote_config: ^5.0.4
  firebase_core: ^3.3.0
  lottie: ^3.0.0
  intl: ^0.19.0
  sizer: ^2.0.15
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.2
  flutter_secure_storage: ^9.2.2
  font_awesome_flutter: ^10.4.0
  flutter_staggered_animations: ^1.1.1
  countup: ^0.1.4
  url_launcher: ^6.1.9
  logger: ^2.4.0
  animated_text_kit: ^4.2.2
  glassmorphism: ^3.0.0
  share_plus: ^10.0.0
  country_code_picker: ^3.0.0
  shared_preferences: ^2.1.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  fluttertoast: ^8.2.8
  intl_phone_number_input: ^0.7.0+2
  video_player: ^2.2.5
  flutter_custom_clippers: ^2.1.0
  flutter_linkify: ^6.0.0
  flutter_dotenv: ^5.1.0
  timer_count_down: ^2.2.2
  circular_countdown_timer: ^0.2.3
  glowy_borders: ^1.0.2
  flutter_swipe_button: ^2.1.3
  flutter_screenutil: ^5.9.3
  list_wheel_scroll_view_nls: ^0.0.3
  audioplayers: ^6.1.0
  google_nav_bar: ^5.0.6
  pin_code_fields: ^8.0.1
  package_info_plus: ^8.0.2
  # connectivity_plus: ^6.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  dart_code_metrics: ^5.6.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
    android: true
    image_path: "assets/images/APP_LOGO.jpeg"

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/video/
        - lib/.env
        - assets/error-music.mp3
        - assets/sci-fi-click.wav

    fonts:
        - family: VT323
          fonts:
              - asset: assets/fonts/VT323-Regular.ttf
        - family: Wallpoet
          fonts:
              - asset: assets/fonts/Wallpoet-Regular.ttf


